/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and kept here so TypeScript knows
// about Next-specific types before the first dev server run.

